name: TestAction1

on:
  push:
  workflow_dispatch:

jobs:
  test-action1:
    runs-on: ubuntu-latest

    steps:
    - id: def
      run: |
        echo "a=2024-09-16" >> $GITHUB_OUTPUT
        echo "b=2024-09-17" >> $GITHUB_OUTPUT
    
    - run: exit 1
    
    - run: echo 2
    
    - run: echo 3
