name: TestAction1

on:
  push:
  workflow_dispatch:

jobs:
  testjob:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - run: |
        date >> actions.log

    - name: GitHub Commit & Push
      uses: actions-js/push@v1.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}


