name: TestAction1

on:
  push:
  workflow_dispatch:

jobs:
  testjob:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: write

    steps:
      - uses: 'actions/checkout@v4'
  
      - run: |
          date | tee -a actions_log.txt
          git add actions_log.txt

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if git commit -m 'Update calendar data'; then
            git push
          else
            echo "No changes to commit"
          fi
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}

    # - name: GitHub Commit & Push
    #   uses: actions-js/push@v1.5
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}











